#
# define compiler and compiler flag variables
#

JFLAGS = -g
JC = javac
JAR_PKG = protocol-labs.jar
TARBALL = protocol-labs.tar.gz

#
# Clear any default targets for building .class files from .java files; we 
# will provide our own target entry to do this in this makefile.
# make has a set of default targets for different suffixes (like .c.o) 
# Currently, clearing the default for .java.class is not necessary since 
# make does not have a definition for this target, but later versions of 
# make may, so it doesn't hurt to make sure that we clear any default 
# definitions for these
#

.SUFFIXES: .java .class


#
# Here is our target entry for creating .class files from .java files 
# This is a target entry that uses the suffix rule syntax:
#	DSTS:
#		rule
#  'TS' is the suffix of the target file, 'DS' is the suffix of the dependency 
#  file, and 'rule'  is the rule for building a target	
# '$*' is a built-in macro that gets the basename of the current target 
# Remember that there must be a < tab > before the command line ('rule') 
#

.java.class:
	$(JC) $(JFLAGS) $*.java


#
# SOURCES files
#

SOURCES = \
	./net/protocol/common/coding/ByteMe.java \
	./net/protocol/common/coding/Message.java \
	./net/protocol/common/exception/EnumValueNotPresentException.java \
	./net/protocol/common/util/Bits.java \
	./net/protocol/common/util/Bytes.java \
	./net/protocol/common/util/DateUtils.java \
	./net/protocol/common/util/Ints.java \
	./net/protocol/common/util/IoUtils.java \
	./net/protocol/common/util/IPSubnet.java \
	./net/protocol/common/util/IPUtils.java \
	./net/protocol/common/util/NtpTime.java \
	./net/protocol/common/util/Pair.java \
	./net/protocol/common/util/StringUtils.java \
	./net/protocol/cops/CopsException.java \
	./net/protocol/cops/CopsFormatErrorException.java \
	./net/protocol/cops/CopsMessageParser.java \
	./net/protocol/cops/message/CopsCAT.java \
	./net/protocol/cops/message/CopsCC.java \
	./net/protocol/cops/message/CopsDEC.java \
	./net/protocol/cops/message/CopsDRQ.java \
	./net/protocol/cops/message/CopsHeader.java \
	./net/protocol/cops/message/CopsKA.java \
	./net/protocol/cops/message/CopsMessage.java \
	./net/protocol/cops/message/CopsOPN.java \
	./net/protocol/cops/message/CopsREQ.java \
	./net/protocol/cops/message/CopsRPT.java \
	./net/protocol/cops/message/CopsSS.java \
	./net/protocol/cops/message/CopsSSC.java \
	./net/protocol/cops/message/CopsSSQ.java \
	./net/protocol/cops/message/IllegalCopsMsgException.java \
	./net/protocol/cops/message/OpCode.java \
	./net/protocol/cops/object/AcctTimer.java \
	./net/protocol/cops/object/ClientSI.java \
	./net/protocol/cops/object/CNum.java \
	./net/protocol/cops/object/Context.java \
	./net/protocol/cops/object/CopsObject.java \
	./net/protocol/cops/object/Dec.java \
	./net/protocol/cops/object/Decision.java \
	./net/protocol/cops/object/Error.java \
	./net/protocol/cops/object/Handle.java \
	./net/protocol/cops/object/Header.java \
	./net/protocol/cops/object/IllegalCopsObjectException.java \
	./net/protocol/cops/object/INInt.java \
	./net/protocol/cops/object/Int.java \
	./net/protocol/cops/object/Integrity.java \
	./net/protocol/cops/object/IpCType.java \
	./net/protocol/cops/object/KATimer.java \
	./net/protocol/cops/object/LastPDPAddr.java \
	./net/protocol/cops/object/LDec.java \
	./net/protocol/cops/object/LPDPDecision.java \
	./net/protocol/cops/object/OUTInt.java \
	./net/protocol/cops/object/PDPAddr.java \
	./net/protocol/cops/object/PDPRedirAddr.java \
	./net/protocol/cops/object/PEPID.java \
	./net/protocol/cops/object/Reason.java \
	./net/protocol/cops/object/ReportType.java \
	./net/protocol/cops/object/Timer.java \
	./org/program/connection/Client.java \
	./org/program/connection/Handler.java \
	./org/program/connection/Server.java 



CLASSES = $(SOURCES:%.java=%.class)

#
# the default make target entry
#

default: classes jar

#
# This target entry uses Suffix Replacement within a macro: 
# $(name:string1=string2)
# 	In the words in the macro named 'name' replace 'string1' with 'string2'
# Below we are replacing the suffix .java of all words in the macro CLASSES 
# with the .class suffix
#

classes: $(SOURCES:.java=.class)

jar:
	jar cvf $(JAR_PKG) $(CLASSES)

tar:
	tar czpf $(TARBALL) $(SOURCES) Makefile


#
# RM is a predefined macro in make (RM = rm -f)
#

clean:
	$(RM) $(CLASSES)  $(JAR_PKG)

